# config.py
SCREEN_WIDTH = 1360
SCREEN_HEIGHT = 768
CALIBRATION_FILE = "calibration.json"
GRID_ROWS = 3
GRID_COLS = 3
SEGMENT_WIDTH = SCREEN_WIDTH // GRID_COLS
SEGMENT_HEIGHT = SCREEN_HEIGHT // GRID_ROWS
FPS = 60
CONF_THRESHOLD = 0.5
IOU_THRESHOLD = 0.7
CLICK_COOLDOWN = 0.5
MODEL_PATH = "best.onnx"
CRACK_IMAGE_PATH = "assets/boom1.png"
CAMERA_WIDTH = 1280
CAMERA_HEIGHT = 720